feat: home page made responsive.
krishnakant01/culerUI pull request #10
Opened 2022-02-10 20:19 UTC by krishnakant01

Hey I've added responsiveness to home page

2022-02-11 02:30 UTC, Kothalkarpriya requested changes
COde looks good, just remove unnecessary spacing and comments

2022-02-11 02:30 UTC, Kothalkarpriya commented on components/navigation/navigation.css
> +
remove unnecessary spacings

2022-02-11 02:30 UTC, Kothalkarpriya commented on docSite-components/docsite-sidebar.css
>      margin: 2rem 2rem 0rem 3rem;
remove comments which are not in use

2022-02-12 05:11 UTC, Nagashree01 approved these changes
Looks good to me. Just remove unnecessary spaces

2022-02-12 06:40 UTC, merged